### ISSUE TITLE
ipynbname way too slow  why?

### ISSUE THREAD

**Issue by jj-github-jj** [msm1089/ipynbname#12]
loading file name takes too long - why?

**Comment by daha96** [comment]
Same problem here, it takes 30 seconds...

**Comment by mullimanko** [comment]
same problem here

**Comment by pnmartinez** [comment]
Similar but different problem here.

We are getting a `FileNotFoundError` in one of our envs (Win11, JupyterLab 3.0.14), and controlling for that as below.

```py
try:
    import ipynbname
    name = ipynbname.name()

except ImportError as e:
    # manage no ipynbname installed

except FileNotFoundError as e:
    # get folder name instead with os.getcwd()

except:
    # general expcetion handler
```

This is controlling the exception properly, but **takes 10 minutes** for the env to return the `FileNotFoundError`.

**Comment by msm1089** [comment]
A timeout of 0.5 seconds has been added in release just now.
