### ISSUE TITLE
"Can't identify the notebook name", jupyterlab version 3.0.14, Windows

### ISSUE THREAD

**Issue by pnmartinez** [msm1089/ipynbname#14]
Hi all,

Discovered this wonderful utility a couple days ago, but a team mate **using Windows is having trouble**.

`--jupyter-lab version: 3.0.14`

```py
...\ipynbname\__init__.py in name()
      80      if path:
      81          return path.stem
--->  82      raise FileNotFoundError(FILE_ERROR.format('name'))
      83
      84

FileNotFoundError: Can't identify the notebook name
```
**Opening new issue as none of the opened ones mention Windows.**

**Comment by msm1089** [comment]
This works on jupyterlab and Windows for me, version 3.6.3. If you still have problems please raise another issue.
