### ISSUE TITLE
broken link in README.md

### ISSUE THREAD

**Issue by laurentperrinet** [msm1089/ipynbname#15]
Hi,

thanks a lot for your project, very useful!

I noticed that this [link is broken](https://msm1089.github.io/2020/09/04/Automating-Jupyter-Notebook-Blog-Post-Deployment.html)

minor :-)

cheers, laurent

**Comment by msm1089** [comment]
Thanks for the catch. I did not end up using this way of blogging in the end. I'll remove the link to avoid confusion :)
