### ISSUE TITLE
Compatibility with VS Code

### ISSUE THREAD

**Issue by jbogar** [msm1089/ipynbname#17]
When the notebook runs in VS Code, `ipynbname` throws an error, but it works fine if the notebook is ran with `jupyter notebook` from terminal.

```
import ipynbname
ipynbname.path()
```
produces:
```
FileNotFoundError                         Traceback (most recent call last)
/Users/jbogar/dummy_notebook.ipynb Cell 2 in <cell line: 2>()
      [1](vscode-notebook-cell:/Users/jbogar/dummy_notebook.ipynb#W1sZmlsZQ%3D%3D?line=0) import ipynbname
----> [2](vscode-notebook-cell:/Users/jbogar/dummy_notebook.ipynb#W1sZmlsZQ%3D%3D?line=1) ipynbname.path()

File ~/opt/miniconda3/lib/python3.8/site-packages/ipynbname/__init__.py:93, in path()
     91     root_dir = Path(srv.get('root_dir') or srv['notebook_dir'])
     92     return root_dir / path
---> 93 raise FileNotFoundError(FILE_ERROR.format('path'))

FileNotFoundError: Can't identify the notebook path.
```

environment:

python == 3.8.13
ipynbname == 2021.3.2
ipykernel  == 6.9.1
VS Code version == 1.70.1

Is that an expected behavior? Any idea why does it happen or how to fix it?

Thanks

**Comment by antdking** [comment]
We're facing similar problems, though it's inconsistent (current theory is the server launches differently when running on Linux, but we don't have the experience to confirm).

As a workaround, the path is [exposed](https://github.com/microsoft/vscode-jupyter/commit/ac1271f1900358c42b10cacfe98e6855dd583032) through a variable

snippet for extracting the path:

```py
from IPython import get_ipython
ip = get_ipython()
path = None
if '__vsc_ipynb_file__' in ip.user_ns:
    path = ip.user_ns['__vsc_ipynb_file__']

path
```

**Comment by msm1089** [comment]
Thanks @antdking - hope that helps others using VS Code!

**Comment by g24swint** [comment]
I would add a "second" to @Diogo-Rossi's recommendation to enable the workaround for VS Code inside of ipynbname

**Comment by Mr-Ruben** [comment]
I'd like to point this out (to save others some time):

This works correctly **only when**:

* **[JupyterLab]** the kernel is started from that specific notebook (whether or not it has been saved to disk).
* **[VS Code]** you are using a notebook that has been **saved to disk** (not a temporary notebook), and the kernel was **started from that saved file**.

---

### VS Code–specific behavior

In other words:

* If you open a **temporary notebook** and start a kernel, `ipynbname` will **not** return the correct path — even if you later save the notebook to disk. [1]
* If you open a notebook and **connect to an already running kernel**, `ipynbname` will also **not** return the correct path.

Instead, `ipynbname` reports the **path of the notebook that originally started the kernel**, not necessarily the one executing the code.

I tried to work around this limitation but couldn’t improve on what `ipynbname` currently provides.

---
[1]

```python
# --- Code ---
import ipynbname
from  pathlib import  Path
Path(ipynbname.path())


# --- Output ---
PosixPath('Untitled-6.ipynb')  # <- Note the path is missing.
```
