### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1

### ISSUE THREAD

**Issue by bingal** [msm1089/ipynbname#18]
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
Cell In[21], line 98
     95         return root_dir / path
     96     raise FileNotFoundError(FILE_ERROR.format('path'))
---> 98 name()

Cell In[21], line 82, in name()
     78 def name() -> str:
     79     """ Returns the short name of the notebook w/o the .ipynb extension,
     80         or raises a FileNotFoundError exception if it cannot be determined.
     81     """
---> 82     _, path = _find_nb_path()
     83     if path:
     84         return path.stem

Cell In[21], line 67, in _find_nb_path()
     65 except (MultipleInstanceError, RuntimeError):
     66     return None, None  # Could not determine
---> 67 for srv in _list_maybe_running_servers():
     68     try:
     69         sessions = _get_sessions(srv)

Cell In[21], line 33, in _list_maybe_running_servers(runtime_dir)
     26     if runtime_dir.is_dir():
     27         for file_name in chain(
     28             runtime_dir.glob('nbserver-*.json'),  # jupyter notebook (or lab 2)
     29             runtime_dir.glob('jpserver-*.json'),  # jupyterlab 3
     30         ):
     31 #             if os.stat(file_name).st_size == 0:
     32 #                 continue
---> 33             yield json.loads(file_name.read_bytes())

File ~/miniconda3/envs/py310/lib/python3.10/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    341     s = s.decode(detect_encoding(s), 'surrogatepass')
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:
    348     cls = JSONDecoder

File ~/miniconda3/envs/py310/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    332 def decode(self, s, _w=WHITESPACE.match):
    333     """Return the Python representation of ``s`` (a ``str`` instance
    334     containing a JSON document).
    335 
    336     """
--> 337     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338     end = _w(s, end).end()
    339     if end != len(s):

File ~/miniconda3/envs/py310/lib/python3.10/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    353     obj, end = self.scan_once(s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

===================================================
-rw-r--r-- 1 support support   0 12月 23 09:32 /home/support/.local/share/jupyter/runtime/nbserver-1020.json
-rw-r--r-- 1 support support   0 12月 23 09:33 /home/support/.local/share/jupyter/runtime/nbserver-1139.json
-rw-r--r-- 1 support support   0 12月 23 09:33 /home/support/.local/share/jupyter/runtime/nbserver-1310.json
-rw-r--r-- 1 support support   0 12月 23 09:33 /home/support/.local/share/jupyter/runtime/nbserver-1310-open.html
-rw-r--r-- 1 support support   0 12月 23 09:34 /home/support/.local/share/jupyter/runtime/nbserver-1382-open.html
-rw-r--r-- 1 support support   0 12月 23 09:34 /home/support/.local/share/jupyter/runtime/nbserver-1449.json
-rw-r--r-- 1 support support   0 12月 23 09:34 /home/support/.local/share/jupyter/runtime/nbserver-1515.json
-rw-r--r-- 1 support support   0 12月 23 09:34 /home/support/.local/share/jupyter/runtime/nbserver-1515-open.html
-rw-r--r-- 1 support support   0 12月 23 09:34 /home/support/.local/share/jupyter/runtime/nbserver-1584-open.html
-rw-r--r-- 1 support support   0 12月 23 09:34 /home/support/.local/share/jupyter/runtime/nbserver-1659.json
-rw-r--r-- 1 support support   0 12月 23 09:35 /home/support/.local/share/jupyter/runtime/nbserver-1726.json
-rw-r--r-- 1 support support   0 12月 23 09:35 /home/support/.local/share/jupyter/runtime/nbserver-1795.json
-rw-r--r-- 1 support support 278 4月  18 2022 /home/support/.local/share/jupyter/runtime/nbserver-18050.json
-rw-r--r-- 1 support support 691 4月  18 2022 /home/support/.local/share/jupyter/runtime/nbserver-18050-open.html
-rw-r--r-- 1 support support 278 1月   9 10:43 /home/support/.local/share/jupyter/runtime/nbserver-19269.json
-rw-r--r-- 1 support support 691 1月   9 10:43 /home/support/.local/share/jupyter/runtime/nbserver-19269-open.html

===================================================
Because There are some nberver json file with 0 size.

When i try add a conform code, then fixed it. `if os.stat(file_name).st_size == 0:`

```python
def _list_maybe_running_servers(runtime_dir=None) -> Generator[dict, None, None]:
    """ Iterate over the server info files of running notebook servers.
    """
    if runtime_dir is None:
        runtime_dir = jupyter_runtime_dir()
    runtime_dir = Path(runtime_dir)

    if runtime_dir.is_dir():
        for file_name in chain(
            runtime_dir.glob('nbserver-*.json'),  # jupyter notebook (or lab 2)
            runtime_dir.glob('jpserver-*.json'),  # jupyterlab 3
        ):
            if os.stat(file_name).st_size == 0:
                continue
            yield json.loads(file_name.read_bytes())
```

**Comment by msm1089** [comment]
Fixed in release just now.

https://github.com/msm1089/ipynbname/blob/021efebf6ec156592386e62919e7d2e00680e1f7/ipynbname/__init__.py#L37
