### ISSUE TITLE
Adding ipynbname to conda-forge

### ISSUE THREAD

**Issue by DamienIrving** [msm1089/ipynbname#6]
I've written a package called [`cmdline-provenance`](https://pypi.org/project/cmdline-provenance/) and I've recently added `ipynbname` as a dependency (thanks, it's a really useful package). I'm in the process of updating the `cmdline-provenance` conda-forge feedstock (see https://github.com/conda-forge/cmdline_provenance-feedstock/pull/1) and a requirement is that all dependencies are also available via conda. 

I was wondering if you have any plans to create a conda-forge feedstock for `ipynbname`? ([These instructions](https://conda-forge.org/docs/maintainer/adding_pkgs.html#dev-contribute-pkgs) explain how to do it.) If not, would you mind if I went ahead and created one for `ipynbname`?

**Comment by msm1089** [comment]
Go ahead Damien, glad it is useful for you :)

**Comment by DamienIrving** [comment]
Great! I've listed both you and I as maintainers of the conda-forge feedstock (although I'm happy to do the work), so if you're happy to be listed as a maintainer you'll just need to write a comment in the following PR saying so:
https://github.com/conda-forge/staged-recipes/pull/14548

**Comment by DamienIrving** [comment]
All done!
https://github.com/conda-forge/ipynbname-feedstock
https://anaconda.org/conda-forge/ipynbname
