### ISSUE TITLE
JupyterHub support

### ISSUE THREAD

**Issue by corymaklin** [msm1089/ipynbname#8]
When running `ipynbname.name()` within a JupyterHub notebook, I get `Can't identify the notebook name`.

**Comment by pacospace** [comment]
Also, interested in this feature. What is ETA for this @msm1089 ? thanks!!!

**Comment by sjdemartini** [comment]
Here's an example someone implemented for getting the notebook name in JupyterHub: https://github.com/jupyterhub/jupyterhub/issues/1718#issuecomment-377036175

**Comment by sjdemartini** [comment]
I've added a very simple PR which makes ipynbname support JupyterHub, utilizing logic like in the above linked example: https://github.com/msm1089/ipynbname/pull/19
