### ISSUE TITLE
Can't identify the notebook name.

### ISSUE THREAD

**Issue by jaewoo-so** [msm1089/ipynbname#9]
I got this error. 

how can i fix it?

import ipynbname
nb_fname = ipynbname.name()

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-89-9b6717ab4e09> in <module>
      1 import ipynbname
----> 2 nb_fname = ipynbname.name()

/ssd/jaewoo/venv/gb2/lib/python3.8/site-packages/ipynbname/__init__.py in name()
     80     if path:
     81         return path.stem
---> 82     raise FileNotFoundError(FILE_ERROR.format('name'))
     83 
     84 

FileNotFoundError: Can't identify the notebook name.`

**Comment by msm1089** [comment]
It only works for some methods of running notebooks unfortunately. Normal jupyter is fine and jupyter lab (up to v3.0.2 at least).

How are you running it, and what versions? I have a bit of time to look into it this week, so will see if I can extend compatibility.

**Comment by Marsdrummer** [comment]
I'm having the same issue. Running Jupyterlab 3.0.16 on Jupyterhub (TLJH).   Error says: 

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/tmp/ipykernel_29100/1504311321.py in <module>
----> 1 nb_fname = ipynbname.name()
      2 nb_fname

/opt/tljh/user/lib/python3.7/site-packages/ipynbname/__init__.py in name()
     80     if path:
     81         return path.stem
---> 82     raise FileNotFoundError(FILE_ERROR.format('name'))
     83 
     84 

FileNotFoundError: Can't identify the notebook name.

**Comment by Marsdrummer** [comment]
Slight update - running on my local machine and Jupyterlab 3.0.14, it works.

**Comment by Marsdrummer** [comment]
@msm1089 any update on this issue? Thanks!

**Comment by msm1089** [comment]
@Marsdrummer I believe the release just now fixes it for JupyterHub. Note that I have not been able to test it on Hub, so if it does not work just add a new issue.
